In [1]:
import numpy as np
import cv2 as cv

(0.707107, 1.224745, -6.928204)
(-0.61548, 0.785398, 0)
### camke  , C++ ,openmp.

In [2]:
P = np.array((0.707107, 1.224745, -6.928204))
R = np.array((-0.61548, 0.785398, 0))
P,R

(array([ 0.707107,  1.224745, -6.928204]),
 array([-0.61548 ,  0.785398,  0.      ]))

In [3]:
D = cv.Rodrigues(R)
print(D[0])
print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
D[0]@P


[[ 0.71633128 -0.22229802  0.66140236]
 [-0.22229802  0.82579535  0.51831037]
 [-0.66140236 -0.51831037  0.54212663]]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


array([-4.34806601, -2.73675972, -4.85844415])

In [4]:
D[0]@P

array([-4.34806601, -2.73675972, -4.85844415])