In [11]:
import numpy as np
import cv2 as cv

(0.707107, 1.224745, -6.928204)
(-0.61548, 0.785398, 0)
(-35.264389, 45, 0)

### camke  , C++ ,openmp.

In [12]:
P = np.array((0.707107, 1.224745, -6.928204))
R = np.array((-0.61548, 0.785398, 0))
P,R

(array([ 0.707107,  1.224745, -6.928204]),
 array([-0.61548 ,  0.785398,  0.      ]))

In [13]:

R_X=np.array( [  [1,0,0],
                [0,np.cos(R[0]),-np.sin(R[0])],
                [0,np.sin(R[0]),np.cos(R[0])]]) 
R_Y=np.array(   [[np.cos(R[1]),0,np.sin(R[1])],
                [0,1,0],
                [-np.sin(R[1]),0,np.cos(R[1])]] )
R_Z=np.array(  [ [np.cos(R[2]),np.sin(R[2]),0],
                [np.sin(R[2]),np.cos(R[2]),0],
                [0,0,1] ])
R_A=R_Z@R_Y@R_X


In [14]:
print(R_X)
print(R_Y)
print(R_Z)
print(R_A)

[[ 1.          0.          0.        ]
 [ 0.          0.81649641  0.57735051]
 [ 0.         -0.57735051  0.81649641]]
[[ 0.7071069   0.          0.70710667]
 [ 0.          1.          0.        ]
 [-0.70710667  0.          0.7071069 ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 0.7071069  -0.40824839  0.57735006]
 [ 0.          0.81649641  0.57735051]
 [-0.70710667 -0.40824853  0.57735024]]


In [15]:
R_A@P

array([-3.99999891, -3.00000219, -5.00000069])