In [1]:
import numpy as np
import cv2 as cv

(0, -0, -12.369316)
(-0.941517, 1.292497, 0)
(-53.944969, 74.054604, 0)
### camke  , C++ ,openmp.

In [2]:
P = np.array((0, -0, -12.369316))
R = np.array((-0.941517, 1.292497, 0))
P,R

(array([  0.      ,   0.      , -12.369316]),
 array([-0.941517,  1.292497,  0.      ]))

In [61]:

R_X=np.array( [  [1,0,0],
                [0,np.cos(R[0]),-np.sin(R[0])],
                [0,np.sin(R[0]),np.cos(R[0])]]) 
R_Y=np.array(   [[np.cos(R[1]),0,np.sin(R[1])],
                [0,1,0],
                [-np.sin(R[1]),0,np.cos(R[1])]] )
R_Z=np.array(  [ [np.cos(R[2]),np.sin(R[2]),0],
                [np.sin(R[2]),np.cos(R[2]),0],
                [0,0,1] ])
R_A=R_Z@R_Y@R_X


In [62]:
print(R_X)
print(R_Y)
print(R_Z)
print(R_A)

[[ 1.          0.          0.        ]
 [ 0.          0.58856228  0.80845188]
 [ 0.         -0.80845188  0.58856228]]
[[ 0.27472081  0.          0.96152404]
 [ 0.          1.          0.        ]
 [-0.96152404  0.          0.27472081]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 0.27472081 -0.77734592  0.56591678]
 [ 0.          0.58856228  0.80845188]
 [-0.96152404 -0.22209855  0.16169031]]


In [63]:
R_A@P

array([-7.0000035 , -9.99999677, -1.99999849])